### PR TITLE
Create workflow to autoupdate IANA TLD lists

### LINKED ISSUE #185: Automate the update of IANA TLD list
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Either run the update and fail CI if changes are detected - Renovate's lock file updates should notify us in this case, or, write something to periodically update and commit the changes where necessary.

### PR DESCRIPTION
**Pull request by Xerkus**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      |no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Workflow to regularly fetch IANA TLD list for Hostname validator and create a PR when update found

Workflow listens for workflow_dispatch and as such it can be manually triggered with `gh workflow run "IANA TLD List Updater" -R laminas/laminas-validator` or via web interface at https://github.com/laminas/laminas-validator/actions/workflows/iana-hostname-list-updater.yml

### CODE REVIEW

**Comment by Xerkus** [comment]
I am not sure if this works but to check it it needs to be on a default branch.
@Ocramius is it acceptable to temporarily switch default branch to something else?

**Comment by Xerkus** [comment]
Workflow run is at https://github.com/laminas/laminas-validator/actions/runs/5081596379/jobs/9130186521
PR opened by workflow is #187

**Review by gsteel — APPROVED** [review]
LGTM 👍

**Comment by Ocramius** [comment]
:ship: thanks @Xerkus @gsteel!

**Pull request merged**
