### PR TITLE
Update IANA TLDs

### PR DESCRIPTION
**Pull request by gsteel**

### CODE REVIEW

**Comment by Ocramius** [comment]
Wait, didn't `.zip` and similar also make it in here?

**Comment by Ocramius** [comment]
@gsteel is it possible to somehow automate this process, or at least make CI fail when a diff is generated here? :thinking:

**Comment by Xerkus** [comment]
Shouldn't be hard to automate. Update script is already there so only scheduled workflow is needed to run script and then create or update PR.

**Comment by gsteel** [comment]
I was just thinking that. Added an issue: https://github.com/laminas/laminas-validator/issues/185

**Comment by gsteel** [comment]
This is redundant now #186 is underway

**Pull request closed without merging**
